org.gradle.jvmargs=-Xmx2G

# BTA
bta_version=7.2_01

# Loader & Mod Menu
# Check the newest version at https://github.com/Turnip-Labs/fabric-loader/releases
loader_version=0.15.6-babric.6-bta
# Check the newest version at https://github.com/Turnip-Labs/ModMenu/releases/
mod_menu_version=2.0.6

# HalpLibe
# Check the newest version at https://github.com/Turnip-Labs/bta-halplibe/releases/
halplibe_version=4.1.3

# Dragonfly
dragonfly_version=1.6.0-7.2-0.1

# Mod
mod_version=0.1.0-7.2
mod_group=teamport
mod_name=creatures
